# Generated by Django 5.1.2 on 2024-10-25 03:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="gender",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="contact_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
