# Generated by Django 5.1.2 on 2024-11-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_alter_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(default="No description available"),
        ),
    ]
