# Generated by Django 5.1.2 on 2024-11-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_alter_category_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="serviceitem",
            name="category",
        ),
        migrations.RemoveField(
            model_name="serviceitem",
            name="image",
        ),
        migrations.AddField(
            model_name="serviceitem",
            name="rating",
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name="serviceitem",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("flower_decoration", "Flower Decoration"),
                    ("catering", "Catering"),
                    ("seating", "Seating"),
                ],
                default="Nothing available, error!",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="serviceitem",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
