# Generated by Django 5.1.2 on 2024-11-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_remove_serviceitem_category_remove_serviceitem_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.CharField(
                choices=[
                    ("flowers", "Flowers"),
                    ("catering", "Catering"),
                    ("seating", "Seating"),
                ],
                max_length=50,
            ),
        ),
    ]
