# Generated by Django 5.1.2 on 2024-11-13 03:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0014_alter_item_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="image",
        ),
        migrations.AddField(
            model_name="item",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
