# Generated by Django 5.1.2 on 2024-11-13 03:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0015_remove_item_image_item_image_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="image_url",
        ),
        migrations.AddField(
            model_name="item",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="items_images/"),
        ),
    ]
