# Generated by Django 5.1.2 on 2024-11-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0016_remove_item_image_url_item_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Item",
        ),
        migrations.AddField(
            model_name="serviceitem",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="items_images/"),
        ),
    ]
