# Generated by Django 5.1.2 on 2024-11-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0019_rename_created_at_order_date_ordered_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceitem",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("flower_decoration", "Flower Decoration"),
                    ("catering", "Catering"),
                ],
                default="Nothing available, error!",
                max_length=50,
            ),
        ),
    ]
