# Generated by Django 5.1.2 on 2024-10-29 01:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("event_bookings", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hall",
            old_name="is_available",
            new_name="availability",
        ),
    ]
