# Generated by Django 5.1.2 on 2024-10-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "event_bookings",
            "0003_remove_hall_availability_hall_available_date_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hall",
            name="available_date",
        ),
        migrations.RemoveField(
            model_name="hall",
            name="available_time",
        ),
        migrations.RemoveField(
            model_name="hall",
            name="event_type",
        ),
        migrations.AlterField(
            model_name="hall",
            name="location",
            field=models.CharField(max_length=50),
        ),
    ]
