# Generated by Django 5.1.2 on 2024-11-21 18:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event_bookings", "0006_hall_is_available"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="booking",
            name="end_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
