# Generated by Django 5.1.2 on 2024-11-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event_bookings", "0007_booking_date_booking_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="payment_status",
            field=models.CharField(default="Pending", max_length=20),
        ),
    ]
