# Generated by Django 5.1.2 on 2024-11-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event_bookings", "0008_booking_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="hall",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
