# Generated by Django 5.1.2 on 2024-11-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event_bookings", "0009_hall_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
