# Generated by Django 5.1.2 on 2024-11-25 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event_bookings", "0010_booking_total_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="payment_method",
            field=models.CharField(blank=True, default="Not Selected", max_length=50),
        ),
    ]
